return {
	"m4xshen/hardtime.nvim",
	dependencies = { "MunifTanjim/nui.nvim", "nvim-lua/plenary.nvim" },
	event = "VeryLazy",
	opts = {
		hint = true,
		max_count = 5,
		disable_mouse = false,
		disabled_keys = {
			["<Up>"] = {},
			["<Down>"] = {},
			["<Left>"] = {},
			["<Right>"] = {},
		},
		restricted_keys = {
			["<Up>"] = {},
			["<Down>"] = {},
			["<Left>"] = {},
			["<Right>"] = {},
		},
		disabled_filetypes = {
			"neo-tree",
			"fugitive",
			"NvimTree",
			"TelescopePrompt",
			"aerial",
			"alpha",
			"checkhealth",
			"dapui*",
			"Diffview*",
			"Dressing*",
			"help",
			"httpResult",
			"lazy",
			"Neogit*",
			"mason",
			"neotest-summary",
			"minifiles",
			"neo-tree*",
			"netrw",
			"noice",
			"notify",
			"prompt",
			"qf",
			"oil",
			"undotree",
			"Trouble",
		},
	},
}
